spring:
  application:
    name: todo-service-app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
#    url: jdbc:mysql://3.219.34.24:3307/ibm
#    username: root
#    password: root
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
server:
  port: 5000